### ISSUE TITLE
Stream encoding should not be set

### ISSUE THREAD

**Issue by vnaking** [mauimauer/nodecast#11]
Error: stream encoding should not be set at makeError (/nodecast/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
    at module.exports (/nodecast/node_modules/body-parser/node_modules/raw-body/index.js:60:15)
    at read (/nodecast/node_modules/body-parser/lib/read.js:62:3)
    at urlencodedParser (/nodecast/node_modules/body-parser/lib/types/urlencoded.js:84:5)
    at /nodecast/node_modules/body-parser/index.js:81:7
    at jsonParser (/nodecast/node_modules/body-parser/lib/types/json.js:75:36)
    at Object.bodyParser [as handle](/nodecast/node_modules/body-parser/index.js:79:5)
    at next (/nodecast/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.logger (/nodecast/node_modules/morgan/index.js:111:5)
    at next (/nodecast/node_modules/express/node_modules/connect/lib/proto.js:193:15)

**Comment by clintandrewhall** [comment]
https://github.com/mauimauer/nodecast/pull/12
