### ISSUE TITLE
Please help, I can't install it

### ISSUE THREAD

**Issue by Barabba11** [mauimauer/nodecast#19]
Hi, thank you for your kind support, 
can you please explain to a stupid person like me how to install it? 
I suppose I have to create a foldere where to put the file server.js and all the content of the zip file, so I did it in C:\nodecast-master, but when I execute it I hacve this output. What is going wrong? Can you please write a detain installation guide for newbies? Thank you a lot!

C:\Windows\System32>node C:\nodecast-master\server.js --name Custom_Chromecast_Name
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'peer-ssdp'
Require stack:
- C:\nodecast-master\server.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:898:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1089:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:73:18)[39m
    at Object.<anonymous> (C:\nodecast-master\server.js:1:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:1200:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1049:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:937:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\nodecast-master\\server.js'[39m ]

**Comment by Barabba11** [comment]
the solution is to run "npm install" inside the folder where are the scripts. It would be lovely to specify this in the installation instructions. 
Anyway it doesn't work because it need to listen to udp 8008 and 8009, it seems is not listening (and my phone can't discover it), only tcp 8008 is opened (and works with browser)
