### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by anthonywebb** [mauimauer/nodecast#2]
I am unable to run the app using node 0.10.15, I did an npm install, and see the following when I run:

Registered App: ChromeCast
Registered App: YouTube
Registered App: PlayMovies
Registered App: GoogleMusic
Registered App: GoogleCastSampleApp
Registered App: GoogleCastPlayer
Registered App: Fling
Registered App: TicTacToe
Express server listening on port 8008

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:124:16)

**Comment by mauimauer** [comment]
Would you mind telling me which OS you're on? Thanks.

**Comment by anthonywebb** [comment]
I am on Mac osx 10.7
- Anthony Webb

On Aug 7, 2013, at 5:24 AM, Sebastian Mauer notifications@github.com
wrote:

Would you mind telling me which OS you're on? Thanks.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mauimauer/nodecast/issues/2#issuecomment-22244477
.

**Comment by wmertens** [comment]
I'm seeing the same on OS X 10.7, Node 0.8, although I have another similar system where it works fine on.

**Comment by GavinJoyce** [comment]
Also seeing this on OSX 10.7.5. Works for me on OSX 10.8.4

**Comment by spike008t** [comment]
That doesn't work for me on OSX 10.8.4 strange...

**Comment by tjwebb** [comment]
Also seeing on OSX 10.8....

**Comment by timvdalen** [comment]
Also on Ubuntu 12.04.3 LTS server edition

**Comment by davidmyers9000** [comment]
Getting the same error on node 0.10.3 on OSX 10.9

**Comment by mbrechet** [comment]
have you check that's only the wifi is enable on your device ? if both ethernet and wifi are enabled this may cause problems

**Comment by timvdalen** [comment]
I don't have WiFi and only one (non-loopback) network interface in total.
