### ISSUE TITLE
Error: Cannot find module 'peer-ssdp'

### ISSUE THREAD

**Issue by swefse** [mauimauer/nodecast#3]
I get this error when running,

node server.js

after having installed npm without issues:

C:\Dev\nodecast-master>node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'peer-ssdp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodecast-master\server.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

I know I'm a total n00b, but I just can't figure it out! Could you help me?

**Comment by badboy** [comment]
Did you type `npm install` in the directory before starting the server?

**Comment by swefse** [comment]
I did now, and it worked! Problem solved. :)
